project:
  type: website
  output-dir: _site

website:
  title: "STAT425"
  google-analytics: "G-H3YKZX4J88"
  page-footer: "\u00a9 2024 Trevor Ruiz"
  navbar:
    background: dark
    foreground: light
    search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

