---
title: "Probability Theory"
date: today
published-title: 'Updated'
---

> Probability is the mathematics of random events. In the context of modern statistics, probability theory provides a framework for studying the properties of samples, estimators, and inferences (the subjects of STAT 426 and STAT 427). This course will cover the axiomatic formulation of probability and formalize familiar concepts, including basic probability rules, random variables, distributions, and expectations. The course will also introduce concepts that play central roles in statistics, such as joint distributions, transformations, and conditional expectations.

Read more in the \[[course syllabus](syllabus.qmd)\].

::: callout-note
## Announcements

-   Late HW12 submissions due 12/2/24 11:59pm PST
:::

**Instructor:** Trevor Ruiz (he/him/his) \[[email](mailto:truiz01@calpoly.edu)\] \[[website](https://tdruiz.com)\]

**Learning assistant:** Edy Reynolds \[[email](mailto:ereyno11@calpoly.edu)\]

**Class meetings:**

-   \[Section 01\] 12:10pm -- 2:00pm MW 186-C300
-   \[Section 02\] 2:10pm -- 4:00pm MW 186-C300

**Office hours (OH) and learning assistant hours (LAH)**:

-   \[OH\] M 4:00pm -- 5:30pm \[[by appointment](https://calendly.com/tdruiz/office-hour)\]

-   \[LAH\] T 11:00am — 12:00pm 25-107G or \[[Zoom](https://calpoly.zoom.us/meeting/tZEqdOmurTotEtGX4FobA8L6G35OPN1365v_/ics?icsToken=98tyKuGtqTgqHNeUtxGCRpwMB4jCc-7ztn5aj7d6pEvDDCJyOi-gEbEXHYJRQYuG&meetingMasterEventId=ntLzXygXQRCCVBmRoXir1g)\]

-   \[OH\] W 9:30am -- 11:00am \[[by appointment](https://calendly.com/tdruiz/office-hour)\]

-   \[LAH\] R 11:00am — 12:00pm 25-107G or \[[Zoom](https://calpoly.zoom.us/meeting/tZEqdOmurTotEtGX4FobA8L6G35OPN1365v_/ics?icsToken=98tyKuGtqTgqHNeUtxGCRpwMB4jCc-7ztn5aj7d6pEvDDCJyOi-gEbEXHYJRQYuG&meetingMasterEventId=ntLzXygXQRCCVBmRoXir1g)\]

For office hours, drop ins are welcome (25-236) but availability is not guaranteed without an appointment. For LA hours, availability is drop-in only on a first come, first served basis.

## Week 1 (9/23/24)

*Set theory; probability axioms*

**Monday:** sets and set operations \[[notes](https://drive.google.com/file/d/1BV2lw1i99VfqqXDc2fmhT0eDnRD5400r/view?usp=share_link)\]

-   \[reading\] sections 1.1, 1.2, 1.2.1
-   \[assignment\] exercises 1.2.1, 1.2.2, 1.2.6 \[[solutions](https://drive.google.com/file/d/1-ZPl6lesXsMRxsEY3ZTxfzRCzZ37o_m7/view?usp=sharing)\]
-   \[optional\] exercises 1.2.5, 1.2.7

**Wednesday:** probability axioms and properties \[[notes](https://drive.google.com/file/d/1X8Te5ySowwIvOEcU_tUgJLIht3z0Aa0I/view?usp=sharing)\]

-   \[reading\] section 1.3
-   \[assignment\] exercises 1.3.6, 1.3.7, 1.3.21, 1.3.22 \[[solutions](https://drive.google.com/file/d/1O2E5hTYmW5gNhJHHqBR78RyCVV7VZkfV/view?usp=sharing)\]
-   \[optional\] exercises 1.3.3, 1.3.5

## Week 2 (9/30/24)

*Discrete probability spaces; counting methods*

**Monday:** counting rules \[[notes](https://drive.google.com/file/d/1kIzbfexKgpRP_uyct13dUr6Xg6xcBRw8/view?usp=sharing)\]

-   \[reading\] section 1.3.1
-   \[assignment\] exercises 1.3.10, 1.3.18, 1.3.19 \[[solutions](https://drive.google.com/file/d/1d-gqfTKikT5_r-JTWNhB6B5crX8WW58_/view?usp=sharing)\]
-   \[optional\] exercises 1.3.14, 1.3.15, 1.3.16

**Wednesday:** the matching problem \[[notes](https://drive.google.com/file/d/1VUalbMiHu-fq1rjcNAwEJvayiGnbVd1l/view?usp=sharing)\]

-   \[reading\] section 1.3.2
-   \[assignment\] exercises 1.3.11, 1.3.14 \[[solutions](https://drive.google.com/file/d/1gZ20TQviytRJrgCJnw3jMF8nkNqoNfzI/view?usp=sharing)\]

## Week 3 (10/7/24)

**Monday**: Quiz 1 \[[clean copy](https://drive.google.com/file/d/1--roA76UoTb5g2Ae2JuyA5g3BLHbXu7M/view?usp=sharing)\]

-   no reading or assignment

**Wednesday**: conditional probability; Bayes' theorem \[[notes](https://drive.google.com/file/d/1-NCNPAIqxe6kRS3EAtfMo6LDNF0CXpjg/view?usp=sharing)\]

-   \[reading\] section 1.4
-   \[assignment\] exercises 1.4.2, 1.4.6, 1.4.8, 1.4.34 \[[solutions](https://drive.google.com/file/d/1PvfRxSJGDcgD0ugtiMkqnVWjvYMeahVF/view?usp=sharing)\]
-   \[optional\] exercises 1.4.4, 1.4.26

## Week 4 (10/14/24)

**Monday**: the Monte Hall problem; independence \[[notes](https://drive.google.com/file/d/1j8qctwElyDWb6mdj-9qwdXs2fyra3ATA/view?usp=sharing)\] \[[R script: sensitivity and specificity](scripts/sensitivity-specificity.R)\]

-   \[reading\] section 1.4.1
-   \[assignment\] exercises 1.4.11, 1.4.21, 1.4.31 \[[solutions](https://drive.google.com/file/d/1ArJ2XXokJmRTkFWoTecuiF_GXLBsMBbg/view?usp=sharing)\]
-   \[optional\] exercises 1.4.12, 1.4.19, 1.4.23, 1.4.26

**Wednesday**: the Gambler's ruin problem; random variables \[[notes](https://drive.google.com/file/d/1XQnzzrvpu7xgOBOIwa09z9dcR6tf8Dnv/view?usp=sharing)\] \[[R script: gambler's ruin simulations](scripts/gamblers-ruin.R)\]

-   \[reading\] section 1.5 through remark 1.5.1 (p. 39)
-   \[assignment\] exercises 1.4.13, 1.4.18, 1.4.22, 1.4.32 \[[solutions](https://drive.google.com/file/d/1Qhdwnd-lz8n_0WCy8KBGtzSE0UlbDU95/view?usp=sharing)\]

## Week 5 (10/21/24)

**Monday**: Quiz 2 \[[clean copy](https://drive.google.com/file/d/1-746sLZ9RpOyDQ4-zp-DuKU5kTtLhv58/view?usp=sharing)\]

-   no reading or assignment

**Wednesday**: distribution functions; discrete random variables and transformations \[[notes](https://drive.google.com/file/d/17SLavdKM19r5rtGK8wSbHhounCSiNW3K/view?usp=sharing)\]

-   \[reading\] remainder of section 1.5, 1.6, 1.6.1
-   \[assignment\] exercises 1.5.4, 1.5.10, 1.6.4, 1.6.7, 1.6.9, 1.6.10 \[[solutions](https://drive.google.com/file/d/1fKApE0urk9T3Nkc-dTkUKrKvv5PwsetQ/view?usp=sharing)\]
-   \[optional\] exercises 1.5.5, 1.5.6, 1.6.8

## Week 6 (10/28/24)

**Monday**: continuous random variables and transformations \[[notes](https://drive.google.com/file/d/11TJFxKNDmgxQ-OsUIt1aOM5Po_UKzpkd/view?usp=sharing)\]

-   \[reading\] section 1.7, 1.7.2
-   \[assignment\] exercises 1.7.6, 1.7.12, 1.7.14, 1.7.23 \[[solutions](https://drive.google.com/file/d/15BlzjPfKBNBI0MU9deM3yuHMiDpXP3P-/view?usp=sharing)\]
-   \[optional\] exercises 1.7.8, 1.7.24, 1.7.25

**Wednesday**: expectations \[[notes](https://drive.google.com/file/d/1EuoKoyHLqdtI7M-0pcnfqPUN-Edvm_ac/view?usp=sharing)\]

-   \[reading\] sections 1.8, 1.9
-   \[assignment\] exercises 1.8.2, 1.8.4, 1.9.3, 1.9.4, 1.9.27 \[[solutions](https://drive.google.com/file/d/15_rM5uMS8oN8-WEQ7mz74AMxq9-qFk78/view?usp=sharing)\]
-   \[optional\] exercises 1.8.6, 1.8.9, 1.9.5, 1.9.8, 1.9.20

## Week 7 (11/4/24)

*Note: daylight savings time ends Sunday 11/3/24*

**Monday**: Quiz 3 \[[clean copy](https://drive.google.com/file/d/1-Hq-WxLCku_fWP4-UX08Ulmukccu0tD6/view?usp=sharing)\]

-   no reading or assignment

**Wednesday**: the standard normal distribution; probability inequalities \[[notes](https://drive.google.com/file/d/1GIAiOF_L_0WK16GQBXZVJHzd0u3EaSOy/view?usp=sharing)\]

-   \[reading\] section 1.10
-   \[assignment\] exercises 1.10.1, 1.10.4, 3.4.1, 3.4.11(a) \[[solutions](https://drive.google.com/file/d/1N-ZIOiimg5mHXvru5iCKDQs4Rx5mEL3F/view?usp=sharing)\]
-   \[optional\] exercises 1.10.2, 1.10.3

## Week 8 (11/12/24)

*Note: Veteran's day observed 11/11/24*

**Monday**: no class meeting (Veteran's day)

**Wednesday**: bivariate distributions and transformations \[[notes](https://drive.google.com/file/d/1aMs6P7Gx3Gk7VJfn3JB0eZWNkOBk7Sdk/view?usp=sharing)\]

-   \[reading\] sections 2.1, 2.1.1, 2.1.2, 2.2
-   \[assignment\] exercises 2.1.7, 2.1.10, 2.2.2, 2.1.11 \[[solutions](https://drive.google.com/file/d/128Mddsuju3Z8112_LplYqcyYpkU2uJku/view?usp=sharing)\]
-   \[optional\] exercises 2.1.1, 2.1.8, 2.2.1

## Week 9 (11/18/24)

**Monday**: conditional distributions \[[notes](https://drive.google.com/file/d/1KTU3lTPgLqObvkprEDeGzwcxoOMmP6La/view?usp=sharing)\]

-   \[reading\] section 2.3
-   \[assignment\] exercises 2.2.3, 2.2.5, 2.3.1, 2.3.3(a) \[[solutions](https://drive.google.com/file/d/1KA-4DIR86UIolJ4w-7cFVNkgaEcwdNms/view?usp=sharing)\]
-   \[optional\] exercises 2.2.4, 2.2.6, 2.2.7 2.3.8, 2.3.10

**Wednesday**: Quiz 4

-   no reading or assignment

## Week 10 (12/2/24)

**Monday**: independence, covariance, and correlation

-   \[reading\] sections 2.4, 2.5
-   \[assignment\] exercises 2.4.1, 2.4.11, 2.5.2, 2.5.3
-   \[optional\] exercises 2.4.7, 2.4.8, 2.4.10, 2.5.4, 2.5.7, 2.5.11

**Wednesday**: random samples

-   \[reading\] section 2.8
-   no assignment (besides studying!)
