---
title: "Course syllabus"
subtitle: "Probability Theory"
author: "STAT425"
author-title: "Course listing"
date: "09/01/2023"
date-format: "MMMM YYYY"
published-title: "Updated"
editor: visual
# format: pdf
---

### Course information

**Instructor:** Trevor Ruiz (he/him/his) \[[email](mailto:truiz01@calpoly.edu)\]

**Class meetings:**

-   \[Section 01/3585\] 4:10pm -- 5:00pm MTWR Construction Innovations Center Room C201
-   \[Section 02/3430\] 5:10pm -- 6:00pm MTWR Construction Innovations Center Room C201

**Office hours:** 1:00pm -- 3:00pm WR 25-236 and [by appointment](https://calendly.com/tdruiz/student)

Probability is the mathematics of random events. It is an active field of study and provides the theoretical foundation for the discipline of statistics. This course aims to formalize familiar probability concepts covered in prior coursework (predominantly STAT 305), including probability rules, random variables, common distributions, and expected value. We will build on prior experience and intuition and develop tools to support deeper inquiry and subsequent study of mathematical statistics in STAT 426 and STAT 427. Students will also be introduced to potentially new concepts that play central roles in statistics such as joint distributions, transformations, and conditional expectation. Lectures will provide an exposition of definitions, properties, theorems, and examples, and offer a venue for discussion; students will practice applying this material to solve probability problems on homework assignments and demonstrate fluency with key concepts on in-class exams.

### Catalog Description

Rigorous development of probability theory. Probability axioms, combinatorial methods, conditional and marginal probability, independence, random variables, univariate and multivariate probability distributions, conditional distributions, transformations, order statistics, expectation and variance. Use of statistical simulation throughout the course. 4 lectures. Prerequisite: MATH 241; MATH 248 or CSC 348; and STAT 305. Recommended: STAT 301.

### Textbook and references

There is no required textbook for the course. However, the overall course organization will closely follow chapters 1 through 4 of DeGroot & Schervish, and exposition of this material will follow Hogg & Craig, which is slightly more formal in style. These books are listed below.

-   (recommended) DeGroot & Schervish, *Probability and Statistics*, 4th edition, Addison-Wesley.

-   (reference) Hogg, McKean, & Craig, *Introduction to Mathematical Statistics*, 8th edition, Pearson.

Desk copies of DeGroot & Schervish are available in StatLab (25-107B).

### Learning outcomes

The course aims to enable students to:

-   use the axiomatic construction of probability to derive properties of probability measures and conditional probability measures, and apply definitions and properties to solve probability problems <!-- CLO 1, 3; EO a -->

-   construct probability models for discrete and continuous random variables, develop familiarity with common probability distributions, and use distribution functions to derive properties such as expectations and variances <!-- CLO 2, 4, 5; EO b, c, e -->

-   determine joint distributions for collections of random variables, and use joint distribution functions to (a) derive properties such as covariance and correlation, (b) to determine conditional and marginal distributions, and (c) derive distributions of transformations and functions of one or more random variables <!-- CLO 6, 7; EO d, f -->

### Assessments

Attainment of learning outcomes will be measured by evaluation of submitted homework assignments and exams. Letter grades will be assigned based on a weighted average of scores, with the relative weighting approximately as indicated in parentheses below.

-   **Homeworks (50%).** Homework assignments will be given approximately weekly (except for exam weeks and holidays). The goal of homework assignments is to provide opportunities for students to reinforce key concepts, definitions, and results through practice and to develop and apply problem-solving abilities. These will be distributed on Thursday each week in which they are assigned and due in class the following Thursday; in general, each assignment will consist of questions pertaining to material discussed in class during the preceding week. Students are encouraged to collaborate on homework assignments, but are expected to prepare submissions individually and indicate in writing on their submission any classmates they collaborated with (see collaboration policy below). Submissions should reflect students' best effort and will be evaluated based on completeness, organization, and correctness of selected answers. Each student's lowest homework score will be omitted in grade calculations; otherwise, all homework scores will be weighted equally.

-   **Midterms (30%).** Two midterm exams will be given during the quarter at approximately four-week intervals as shown on the tentative schedule below. The goal of the midterm exams is to assess students' ability to use key concepts, definitions, and results in furtherance of course learning outcomes. Midterms will be given in class on Thursdays during indicated weeks and consist of 2-3 questions that must be answered individually during the allotted time without consulting anyone except the instructor. Students will be allowed one sheet of notes that they may consult while taking each exam. Answers will be evaluated based on completeness and correctness. While both midterm exams will count towards final grades, whichever exam receives the higher score will be weighted more heavily in grade calculations.

-   **Final (20%).** A final exam will be given in the usual classroom at the time scheduled by the registrar. The goal of the final exam is to assess students' integration of the course material in furtherance of course learning oucomes. For Section 01, the final will be held on Wednesday, December 13, 4:10pm --- 7:00pm; for Section 02, the final will be held on Friday, December 15, 4:10pm --- 7:00pm. The final will consist of 4-6 questions that must be answered individually during the allotted time without consulting anyone except the instructor. Students will be allowed one sheet of notes that they may consult while taking the final. Its scope will be cumulative but emphasis will be on later material. Answers will be evaluated based on completeness and correctness.

Every effort will be made to return evaluated work within one week of submission. Final exams, per University policy, will be retained by the instructor. Scores will be recorded in Canvas, and students will be responsible for checking their scores to ensure accurate data entry upon receipt of evaluated work.

Very roughly, letter grades will be assigned as follows. A: 90-100. B: 75-90. C: 60-75. D: 50-60. However, please note that [letter grades represent *qualitative* assessments of attainment of course objectives](https://catalog.calpoly.edu/academicstandardsandpolicies/grading/), and as such these ranges may be adjusted at instructor discretion to ensure apporpriate correspondence with letter grade definitions based on course assessments. Please also note that failure to adhere to course policies --- particularly collaboration, academic integrity, and attendance policies --- may result in a lower letter grade than would otherwise be assigned.

### Tentative schedule

Subject to change at instructor discretion.

| Week                 | Lecture Topic                            | Suggested reading | Assignments |
|----------------|-------------------------|----------------|----------------|
| 0 (9/21)             | Course introduction                      |                   |             |
| 1 (9/25)             | Probability axioms and properties        | 1.4--1.6          | HW1         |
| 2 (10/2)             | Counting methods                         | 1.7--1.10         | HW2         |
| 3 (10/9)             | Conditional probability and independence | 2.1--2.2          | HW3         |
| 4 (10/16)            | Bayes' theorem                           | 2.3--2.4          | Midterm 1   |
| 5 (10/23)            | Discrete and continuous random variables | 3.1--3.3          | HW4         |
| 6 (10/30)            | Joint and conditional distributions      | 3.4--3.7          | HW5         |
| 7 (11/6)             | Transformations and order statistics     | 3.8--3.9          | HW6         |
| 8 (11/13)            | Expectation                              | 4.1--4.2          | Midterm 2   |
| *Fall break (11/20)* |                                          |                   |             |
| 9 (11/27)            | Variance and covariance                  | 4.3, 4.6          | HW7         |
| 10 (12/4)            | Conditional expectation                  | 4.7               |             |
| *Finals (12/11)*     |                                          |                   | Final       |

### Course policies

#### Collaboration

Collaboration within the class (including across class sections) is allowed (and encouraged!) on homework assignments, subject to certain conditions outlined in the paragraph below. Collaborations should not include individuals outside of the class. Students collaborating with a group are expected to prepare their own solutions, in their own words and writing, and should to indicate their collaborators in writing on their submission. This is limited to peers that were consulted closely in completing the assignment; brief or passing interactions are not considered collaborations.

A collaboration is a shared effort. Students that choose to work together on homework assignments are expected to make material contributions towards producing one or more shared answers or solutions. Material contributions might include participation in discussions, critique of a proposed solution, or presentation of a problem approach. In the absence of such contributions, submitting solutions prepared in a group is not appropriate. The best way to adhere to this policy is to attempt problems individually before consulting others.

#### Attendance

Regular attendance is essential for success in the course and required per University policy. Each student may miss two class meetings without notice but additional absences should be [excusable](https://academicprograms.calpoly.edu/content/academicpolicies/class-attendance) and students should notify the instructor. Frequent unexcused absences may negatively impact course grades.

#### Communication and email

Students are encouraged to use face-to-face means of communication (office hours, class meetings, appointments) when possible. Email may be used on a secondary basis or when a written record of communication is needed. Every effort is made to respond to email within 48 weekday hours --- so a message sent Thursday or Friday may not receive a reply until Monday or Tuesday. Time-sensitive messages should be identified as such in the subject line. Students should wait one week before sending a reminder.

#### Time commitment

STAT425 is a four-credit course, which corresponds to a minimum time commitment of 12 hours per week, including lectures, reading, homework assignments, and study time. Some variability in workload by week should be expected, and most students will need to budget a few extra hours each week. However, students can expect to be able to meet course expectations with a time commitment less than 16 hours per week, and are encouraged to notify the instructor if they are regularly exceeding this amount.

#### Assignment scores and final grades

Every effort will be made to provide consistent and fair evaluation of student work. Students should notify the instructor of any errors and/or discrepancies in evaluation promptly and on an assignment-by-assignment basis (*i.e.,* not at the end of the quarter) to guarantee consideration for correction. Final grades will only be changed in the case of clerical errors. Attempting to negotiate scores or final grades is not appropriate. Per University policy, faculty have final responsibility for grading criteria and grading judgment and have the right to alter student assessment or other parts of the syllabus during the term. If any student feels their grade is unfairly assigned at the end of the course, they have the right to appeal it according to the procedure outlined [here](https://academicprograms.calpoly.edu/content/academic-petition-appeals).

#### Late work

Each student may turn in two homework assignments up to one week late without penalty at any time during the quarter and without notice. Subsequently, assignments turned in up to one week late will be evaluated for 75% credit unless an extension is granted in advance. No late work will be accepted beyond one week after the original due date. This policy applies to homework assignments only, and not exams.

#### Accommodations

It is University policy to provide, on a flexible and individualized basis, reasonable accommodations to students who have disabilities that may affect their ability to participate in course activities or to meet course requirements. Accommodation requests should be made through the [Disability Resource Center](https://drc.calpoly.edu) (DRC).

#### Conduct and Academic Integrity

Students are expected to be aware of and adhere to University policy regarding academic integrity and conduct. Detailed information on these policies, and potential repercussions of policy violations, can be found via the [Office of Student Rights & Responsibilities](https://osrr.calpoly.edu) (OSRR).

#### Copyright and distribution of course materials

All course materials, including handouts, homework assignments, study guides, course notes, exams, and solutions are subject to copyright; students are not permitted to share or distribute any course materials without the explicit written consent of the instructor. This includes, in particular, uploading materials or prepared solutions to online services and sharing materials or prepared solutions with students who may take the course in a future term. Transgressions of this policy compromise the effectiveness of course assessments and do a disservice to future students.
