---
title: "Common distributions"
format:
  latex: default
---

+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Name               | PDF/PMF                                                                    | Support               | Parameters                       | Mean                 | Variance                                      | MGF                                                                                     |
+====================+============================================================================+=======================+==================================+======================+===============================================+=========================================================================================+
| Discrete uniform   | $\frac{1}{n}$                                                              | $\{a_1, \dots, a_n\}$ | none                             | $\bar{a}$            | $\frac{1}{n}\sum_{i = 1}^n (a_i - \bar{a})^2$ | $\frac{1}{n}\sum_{i = 1}^n e^{ta_i}$                                                    |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Bernoulli          | $p^x (1 - p)^{1 - x}$                                                      | $\{0, 1\}$            | $p \in (0, 1)$                   | $p$                  | $p(1 - p)$                                    | $1 - p + pe^t$                                                                          |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Geometric          | $(1 - p)^x p$                                                              | $\mathbb{N}$          | $p \in (0, 1)$                   | $\frac{1 - p}{p}$    | $\frac{1 - p}{p^2}$                           | $\frac{p}{1 - (1 - p)e^t}$                                                              |
|                    |                                                                            |                       |                                  |                      |                                               |                                                                                         |
|                    |                                                                            |                       |                                  |                      |                                               | $t < -\log(1 - p)$                                                                      |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Binomial           | ${n \choose p} p^x (1 - p)^{n - x}$                                        | $\{0, 1, \dots, n\}$  | $n \in \mathbb{Z}^+$             | $np$                 | $np(1 - p)$                                   | $\left(1 - p + pe^t\right)^n$                                                           |
|                    |                                                                            |                       |                                  |                      |                                               |                                                                                         |
|                    |                                                                            |                       | $p \in (0, 1)$                   |                      |                                               |                                                                                         |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Negative binomial  | ${r + x - 1 \choose x} p^r (1 - p)^x$                                      | $\mathbb{N}$          | $r \in \mathbb{Z}^+$             | $\frac{r(1 - p)}{p}$ | $\frac{r(1 - p)}{p^2}$                        | $\left(\frac{p}{1 - (1 - p)e^t}\right)^r$                                               |
|                    |                                                                            |                       |                                  |                      |                                               |                                                                                         |
|                    |                                                                            |                       | $p \in (0, 1)$                   |                      |                                               | $t < -\log(1 - p)$                                                                      |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Poisson            | $\frac{\lambda^xe^{-\lambda}}{x!}$                                         | $\mathbb{N}$          | $\lambda > 0$                    | $\lambda$            | $\lambda$                                     | $\exp\left\{-\lambda(1 - e^t)\right\}$                                                  |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Continuous uniform | $\frac{1}{b - a}$                                                          | $(a, b)$              | $-\infty < a < b < \infty$       | $\frac{b + a}{2}$    | $\frac{(b - a)^2}{12}$                        | $\begin{cases}\frac{e^{ta} - e^{tb}}{t(b - a)} &,\;t\neq 0 \\ 1 &,\; t = 0 \end{cases}$ |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Gaussian           | $\frac{1}{\sqrt{2\pi\sigma^2}} e^{-\frac{1}{2\sigma^2} (x - \mu)^2}$       | $\mathbb{R}$          | $\mu \in \mathbb{R}, \sigma > 0$ | $\mu$                | $\sigma^2$                                    | $\exp\left\{\mu t + \frac{1}{2}t^2\sigma^2\right\}$                                     |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Gamma              | $\frac{1}{\Gamma(\alpha)\beta^\alpha} x^{\alpha - 1} e^{-\frac{x}{\beta}}$ | $x > 0$               | $\alpha > 0, \beta > 0$          | $\alpha\beta$        | $\alpha\beta^2$                               | $\left(1 - \beta t\right)^{-\alpha}$                                                    |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
