---
title: "Homework 2"
author: "STAT425, Fall 2023"
author-title: "Course"
date: "10/12/2023"
published-title: "Due in class on"
# format: pdf
---

Please prepare your solutions neatly, numbered, and in order; ideally, you'll write up a final clean copy after completing all problems on scratch paper. Please note that if a prompt includes a question, you're expected to support answers with reasoning, even if the prompt does not explicitly ask for a justification. Provide your name at the top of your submission, and if you collaborate with other students in the class, please list their names at the top of your submission beneath your own.

1.  (Hypergeometric distribution) Imagine a clown car with 50 clowns; suppose that 20 of them are happy clowns and 30 of them are sad clowns.

    i.  If 10 clowns exit the car sequentially and at random, what is the probability that exactly 3 are sad clowns?
    ii. If 10 clowns exit the car sequentially and at random, what is the probability that exactly $k$ are sad clowns? (Assume $0\leq k \leq 10$.)
    iii. If $n$ clowns exit the car sequentially and at random, what is the probability that exactly $k$ are sad clowns? (Assume $0 \leq k \leq n$ and $n < 50$.)
    iv. If the car contains $N$ happy clowns and $M$ sad clowns and $n \leq N + M$ exit the car sequentially and at random, what is the probability that $k$ are happy clowns (for $0 \leq k \leq n$)?

2.  Consider rolling two six-sided dice. The sample space is $S = \{1, 2, 3, 4, 5, 6\}^2$. Assuming the dice are fair, each outcome $(i, j)$ has equal probability $p$. Consider the event that the dice sum to $k$: $E_k = \{(i, j)\in S: i + j = k\}$.

    i.  Find $|S|$ and $p$.
    ii. Find $|E_k|$ in terms of $k$.
    iii. Make a table of the probabilities $P(E_k)$.
    iv. Interpret the event $\bigcup_{k = 1}^m E_k$ in words and find $P\left(\bigcup_{k = 1}^m E_k\right)$ (assuming $1\leq m \leq 12$).
    v.  Find the probability of rolling a sum smaller than or equal to 8.

*Hint*: you may find the proof of SWR2 helpful in answering part (ii); however, there are multiple ways to solve the problem.

3.  Verify the following identities.

    i.  ${n \choose k} = (k + 1){n \choose k + 1}$
    ii. ${n + m \choose m} = {n + m \choose n}$
    iii. ${n \choose 1} = {n \choose n - 1} = n$
    iv. ${n \choose k} = {n \choose n - k}$
    v.  ${n \choose k} = \frac{n}{k}{n - 1 \choose k - 1}$

4.  Consider a lottery where players can choose 12 numbers between 0 and 50 (including 0 and 50) and one winning combination is drawn by randomly selecting one number at a time. Suppose there are three prizes: the biggest prize is awarded to a match of all numbers in the winning combination in sequence; the second biggest prize is awarded to a match of all numbers in the winning combination, but not in sequence; and a smaller cash prize is awarded for matching all but one number in the winning combination, and not necessarily in sequence.

    i.  What is the probability of winning each prize if player selections (and the winning combination) can include each number no more than once?
    ii. What is the probability of winning each prize if player selections (and the winning combination) can include any number multiple times?
    iii. What is the probability of winning any of the prizes under each of the scenarios in (i) and (ii)?

5.  Suppose that you have $n$ letters addressed to distinct recipients and $n$ envelopes addressed accordingly, and the letters are placed in the envelopes at random and mailed. Let $A_i = i\text{th letter is placed in the correct envelope}$.

    i.  Find the probability that the $i$th letter is placed in the correct envelope: determine $P(A_i)$.
    ii. Find the probability that the $i$th and $j$th letters are placed in the correct envelopes: determine $P(A_i \cap A_j)$ assuming $1 \leq i < j \leq n$.
    iii. Find $\sum_{1 \leq i < j \leq n} P(A_i \cap A_j)$. (*Hint*: how many ways are there to choose two letters?)
    iv. Find the probability that the $i$th, $j$th, and $k$th letters are placed in the correct envelopes: determine $P(A_i \cap A_j \cap A_k)$ assuming $1 \leq i < j < k \leq n$.
    v.  Find $\sum_{1 \leq i < j < k \leq n} P(A_i \cap A_j \cap A_k)$. (*Hint*: how many ways are there to choose three letters?)
    vi. Find the probability that an arbitrary subcollection of $i$ letters (say, letters $j_1, \dots, j_i$) are all placed in the right envelopes: determine $P(A_{j_1}\cap A_{j2} \cap \cdots \cap A_{ji})$ assuming $1 \leq j_1 < \cdots < j_i \leq n$.
    vii. Find $\sum_{1 \leq j_1 < \cdots < j_i \leq 1} P(A_{j_1} \cap \cdots \cap A_{j_i})$.
    viii. Use the inclusion-exclusion formula to find the probability that at least one letter is mailed to the correct recipient. What is the limit of this probability as $n \rightarrow \infty$?
