---
title: "Homework 6"
author: "STAT425, Fall 2023"
author-title: "Course"
date: "11/16/2023"
published-title: "Due in class on"
# format:
#   latex:
#     include-in-header:
#       - text:
#           \usepackage{fancyhdr}
#     include-before-body:
#       - text:
#           \pagestyle{fancy}
#           \fancyhead[LH]{HW6}
#           \fancyhead[RH]{STAT425, Fall 2023}
---

Please prepare your solutions neatly, numbered, and in order; ideally, you'll write up a final clean copy after completing all problems on scratch paper. Please note that if a prompt includes a question, you're expected to support answers with reasoning, even if the prompt does not explicitly ask for a justification. Provide your name at the top of your submission, and if you collaborate with other students in the class, please list their names at the top of your submission beneath your own.

1.  (Normal-$\chi^2$ relationship) Show that if $Z\sim N(0, 1)$ then $Z^2 \sim \chi^2_1$.

2.  (Stochastic ordering) Two random variables $X$ and $Y$ are stochastically ordered if either $F_X(x) \geq F_Y(x)$ or the reverse inequality is true for every $x \in \mathbb{R}$. If $F_X(x) \geq F_Y(x)$ for every $x\in\mathbb{R}$, then $X \leq_{st} Y$. Show that the exponential distribution is stochastically ordered in its parameter: that is, if $X \sim \text{exponential}(\alpha)$ and $Y \sim \text{exponential}(\alpha + c)$, then $X \geq_{st} Y$. (Use the 'rate' parametrization: $f(x) = \alpha e^{-\alpha x}, x > 0, \alpha > 0$.

<!-- (Lognormal density) Let $\log X \sim N(\mu, \sigma^2)$. Find the PDF of $X$ and show that $e^\mu$ is a median of $X$, *i.e.*, $P(X \leq e^\mu) \geq \frac{1}{2}$ and $P(X > e^\mu) \leq \frac{1}{2}$. -->

<!-- 3.  Let $X$ be a discrete random variable. Show that if the $k$th moment exists, then so does the $j$th moment for every integer $j \leq k$. -->

3.  Let $X$ be a random variable with moment generating function $m_X (t)$. Define $s_X (t) = \log\left(m_X(t)\right)$. Show that $s'_X(0) = \mathbb{E}X$ and $s_X''(0) = \text{var}(X)$. Then use this approach to find the mean and variance of a random variable $X$ when:

    i.  $X\sim N(\mu, \sigma^2)$
    ii. $X \sim \Gamma(\alpha, \beta)$
