---
title: "Midterm 1 study guide"
author: "STAT425, Fall 2023"
author-title: "Course"
date: today
published-title: "Updated"
# format: 
#   latex:
#     include-in-header: 
#       - text: 
#           \usepackage{fancyhdr}
#     include-before-body:
#       - text:
#           \pagestyle{fancy}
#           \fancyhead[LH]{HW2}
#           \fancyhead[RH]{STAT425, Fall 2023}
---

This may be updated with further advice, suggestions, and the like --- check back.

### Midterm details and scope

The midterm exam will be given in class on Thursday, October 19. Here are the logistical details:

-   50 minutes in duration
-   you're allowed one double-sided note sheet on standard 8.5 x 11 paper
-   scratch paper will be available
-   3 problems in length
-   no calculator required

Problems will draw on material from weeks 1-3, plus material covered Monday of week 4. You can expect one probability rules problem (week 1), one counting problem (week 2), and one conditional probability problem (week 3). Problems will emphasize application of course concepts; you need not expect to write

### Topics to review

#### Probability rules

-   set concepts and operations

-   set cardinality

-   DeMorgan's laws

-   events, disjoint events, partitions

-   probability axioms

-   probability rules

    -   finite additivity
    -   complement rule
    -   monotonicity
    -   union rule
    -   limits for monotone sequences of events
    -   countable sub-additivity (Boole's inequality)
    -   finite sub-additivity
    -   Bonferroni's inequality

-   construction of probability measures on finite sample spaces

#### Counting

-   multiplication rules for counting

-   counting rules for combinations of elements drawn from a finite set

    -   ordered and drawn with replacement
    -   ordered and drawn without replacement
    -   unordered and drawn with replacement
    -   unordered and drawn without replacement

#### Conditional probability

-   definition of conditional probability

-   multiplication rules for conditional probability

-   law of total probability

-   definition of independence, pairwise independence, and mutual independence

-   Bayes' theorem

-   odds form of Bayes' theorem

### Example problems

1.  Suppose you are performing $k$ hypothesis tests at exact level $\alpha$, and assume all hypotheses are true. In other words, if $R_i$ denotes the event that the $i$th hypothesis is rejected, *i.e.*, of making an error, then $P(R_i) = \alpha$. However, when considering the tests as a group, there is a higher probability of making an error, as the individual error rates compound.It can be shown from the inclusion-exclusion principle that: $$
    P\left(\bigcup_{i = 1}^k R_i\right) \geq \sum_{i = 1}^k P(R_i) - \sum_{1 \leq i < j \leq k} P(R_i \cap R_j)
    $$
    i.  Use Boole's inequality to find an upper bound for the probability of making at least one error.
    ii. Use the fact above to derive a lower bound for the probability of making at least one error, assuming that the tests are independent.
    iii. Find the probability of making at least one error when performing 20 tests at $\alpha = 0.05$.
    iv. Find the smallest number of tests for which the probability of making at least one error is more likely than not. (Hint: write $0.05$ as $\frac{5}{100}$; you may find it useful to know that $41^2 = 1681$.)

*Remark*: this last part is maybe a little more involved in terms of calculation than what I'd put on an exam.

2.  Suppose you are reading an article on admission rates at a selective college for different demographic groups reporting that 20% of applicants from underrepresented groups were admitted in 2022-2023 compared with 10% of other applicants.

    i.  What is the probability that a randomly selected incoming student is from an underreppresented group if there were twice as many applicants from non-underrepresented groups?
    ii. What is the probability that a randomly selected incoming student is from an underrepresented group if there were ten times as many applicants from non-underrepresented groups?
    iii. Under the scenario in (i), find the probability that a randomly selected applicant was admitted.

3.  Imagine you're out trick-or-treating with a friend and you arrive at a house handing out only two treats: Kit Kats and Snickers. The homeowner has mixed them up in a large pillowcase. You and your friend can each draw $n$ pieces of candy; assume either treat is equally likely to be selected on each draw. Supposing that when you arrive, there are $N > 2n$ Snickers and $M > 2n$ Kit Kats, and you draw first, find an expression for the probability that you draw $k_1$ Snickers and your friend draws $k_2$ Snickers.

*Extra practice*: find an expression for the probability that your friend draws $k_2$ Snickers.

### Suggestions

Review your notes, homeworks, and the posted lecture notes. Think a bit about what would be most useful to put on your note sheet, and consider prioritizing (i) things you are likely to forget (counting formulae, for instance) and (ii) definitions or results you'd like to have handy for reference (*e.g.*, definition of conditional probability). You don't need to use all of the space you're allowed; sometimes fewer notes that are easier to navigate are more useful than dense notes.

Try some example problems from the book. Look to the end of chapters 1 and 2, and pick a few that seem comfortable and relate to specific material you'd like to practice. No need to choose difficult problems --- this can actually be counterproductive. Remember, you want practice and repetition, not a struggle.

When you sit to take the test, read the whole exam first before beginning work. Take a moment to think, and start with the problem you feel most confident in --- this can help to build a bit of momentum to carry you through any portions you find challenging.
