---
title: "Midterm 2 study guide"
author: "STAT425, Fall 2023"
author-title: "Course"
date: today
published-title: "Updated"
# format: 
#   latex:
#     include-in-header: 
#       - text: 
#           \usepackage{fancyhdr}
#     include-before-body:
#       - text:
#           \pagestyle{fancy}
#           \fancyhead[LH]{HW2}
#           \fancyhead[RH]{STAT425, Fall 2023}
---

This may be updated with further advice, suggestions, and the like --- check back.

### Midterm details and scope

The midterm exam will be given in class on Thursday, November 16. Here are the logistical details:

-   50 minutes in duration
-   you're allowed one double-sided note sheet on standard 8.5 x 11 paper
-   scratch paper will be available
-   3 problems in length
-   no calculator required, but calculators allowed
-   a table of common distributions will be provided

The exam will focus on material covered since the last exam, *i.e.*, from weeks 4 through 7: random variables, common distributions, and expectation. Questions will focus on your ability to use distribution functions (CDF, PDF/PMF, MGF) to characterize distributions of random variables and find expected values. You can expect at least one question to require you to apply these concepts in the context of an unfamiliar distribution.

### Topics for review

For this exam, you should be prepared to demonstrate you understand the following:

-   definition of a random variable
-   definition and properties of the cumulative distribution function
-   distinction between discrete and continuous random variables
-   definition and properties of the probability mass function and the probability density function
-   definition and properties of expected value
-   how to compute expectations of functions of discrete and continuous random variables
-   definition of variance
-   how to compute the variances of discrete and continuous random variables
-   definition and use of moment generating functions
-   PDF/PMFs, expectations, variances, and moment generating functions for common probability distributions
-   properties of the Gaussian distribution

Please note that you will be provided with a table of the distributions we covered in class, so you do not need to include these on your note sheet.

### To prepare

Review posted course notes, focusing especially on definitions, results (lemma, theorem, corollary), and keywords in blue appearing *outside* of the proof and example boxes. Consult also your notes from class; see if you can boil the main ideas and results down to a few pages of notes. Skim the examples and identify which results and concepts are being used in each example. While you're not responsible for reproducing the proofs or calculations that we cover in class, they do illustrate useful techniques that may come in handy.

### Practice problems

The problems below vary in length and difficulty.

1.  Let $\log X \sim N(\mu, \sigma^2)$. If $k$ is an arbitrary positive integer, find an expression for $\mathbb{E}X^k$ and use it to compute the first three moments.

2.  Intuitively, a log transformation should reduce the skewness of a distribution. The skewness of a random variable is defined as the third standardized moment, i.e., the expectation $\mathbb{E}\left[\left(\frac{X - \mu}{\sigma}\right)^3\right] = \frac{\mu_3 - 3\mu_1\sigma^2 - \mu_1^3}{\sigma^3}$, where $\mu_k$ denotes the $k$th moment and $\sigma$ denotes the square root of the variance, i.e., $\sigma = \sqrt{\mu_2 - \mu_1^2}$. Let $\log(X) \sim N(0, 1)$; show that the skewness of $X$ is larger than the skewness of $\log(X)$.

3.  Show that the skewness of a gamma random variable decreases with the value of the parameter $\alpha$.

4.  Let $\log(X) \sim \Gamma(\alpha, \beta)$. Find the mean and variance of $X$.

5.  Suppose that you have an hour to answer letters each day, and the number of letters that arrive follows a Poisson distribution. If $k$ letters arrive, you can dedicate $\frac{1}{k}$ hours to answering each letter. What is the distribution of answering times? Let $X \sim \text{Poisson}(\lambda)$ and $Y = \frac{1}{X}$. Find the PMF of $Y$.

6.  Let $f(x) = c\left[1 - (x - 1)^2\right]$. Find the value of $c$ and support set for which $f$ is a PDF.

7.  Let $X \sim \text{exponential}(\beta)$ and $c > 0$ and define $$
    Y = \begin{cases}
      1 &,\; X > c \\
      0 &,\; X \leq c
    \end{cases}
    $$ Find the distribution of $Y$ and its mean and variance.
    
Textbook problems: 

### Common distributions

You will have access during the test to this table of common distributions.

+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Name               | PDF/PMF                                                                    | Support               | Parameters                       | Mean                 | Variance                                      | MGF                                                                                     |
+====================+============================================================================+=======================+==================================+======================+===============================================+=========================================================================================+
| Discrete uniform   | $\frac{1}{n}$                                                              | $\{a_1, \dots, a_n\}$ | none                             | $\bar{a}$            | $\frac{1}{n}\sum_{i = 1}^n (a_i - \bar{a})^2$ | $\frac{1}{n}\sum_{i = 1}^n e^{ta_i}$                                                    |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Bernoulli          | $p^x (1 - p)^{1 - x}$                                                      | $\{0, 1\}$            | $p \in (0, 1)$                   | $p$                  | $p(1 - p)$                                    | $1 - p + pe^t$                                                                          |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Geometric          | $(1 - p)^x p$                                                              | $\mathbb{N}$          | $p \in (0, 1)$                   | $\frac{1 - p}{p}$    | $\frac{1 - p}{p^2}$                           | $\frac{p}{1 - (1 - p)e^t}$                                                              |
|                    |                                                                            |                       |                                  |                      |                                               |                                                                                         |
|                    |                                                                            |                       |                                  |                      |                                               | $t < -\log(1 - p)$                                                                      |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Binomial           | ${n \choose p} p^x (1 - p)^{n - x}$                                        | $\{0, 1, \dots, n\}$  | $n \in \mathbb{Z}^+$             | $np$                 | $np(1 - p)$                                   | $\left(1 - p + pe^t\right)^n$                                                           |
|                    |                                                                            |                       |                                  |                      |                                               |                                                                                         |
|                    |                                                                            |                       | $p \in (0, 1)$                   |                      |                                               |                                                                                         |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Negative binomial  | ${r + x - 1 \choose x} p^r (1 - p)^x$                                      | $\mathbb{N}$          | $r \in \mathbb{Z}^+$             | $\frac{r(1 - p)}{p}$ | $\frac{r(1 - p)}{p^2}$                        | $\left(\frac{p}{1 - (1 - p)e^t}\right)^r$                                               |
|                    |                                                                            |                       |                                  |                      |                                               |                                                                                         |
|                    |                                                                            |                       | $p \in (0, 1)$                   |                      |                                               | $t < -\log(1 - p)$                                                                      |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Poisson            | $\frac{\lambda^xe^{-\lambda}}{x!}$                                         | $\mathbb{N}$          | $\lambda > 0$                    | $\lambda$            | $\lambda$                                     | $\exp\left\{-\lambda(1 - e^t)\right\}$                                                  |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Continuous uniform | $\frac{1}{b - a}$                                                          | $(a, b)$              | $-\infty < a < b < \infty$       | $\frac{b + a}{2}$    | $\frac{(b - a)^2}{12}$                        | $\begin{cases}\frac{e^{ta} - e^{tb}}{t(b - a)} &,\;t\neq 0 \\ 1 &,\; t = 0 \end{cases}$ |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Gaussian           | $\frac{1}{\sqrt{2\pi\sigma^2}} e^{-\frac{1}{2\sigma^2} (x - \mu)^2}$       | $\mathbb{R}$          | $\mu \in \mathbb{R}, \sigma > 0$ | $\mu$                | $\sigma^2$                                    | $\exp\left\{\mu t + \frac{1}{2}t^2\sigma^2\right\}$                                     |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
| Gamma              | $\frac{1}{\Gamma(\alpha)\beta^\alpha} x^{\alpha - 1} e^{-\frac{x}{\beta}}$ | $x > 0$               | $\alpha > 0, \beta > 0$          | $\alpha\beta$        | $\alpha\beta^2$                               | $\left(1 - \beta t\right)^{-\alpha}$                                                    |
+--------------------+----------------------------------------------------------------------------+-----------------------+----------------------------------+----------------------+-----------------------------------------------+-----------------------------------------------------------------------------------------+
