---
title: "Homework 7"
author: "STAT425, Fall 2023"
author-title: "Course"
date: "12/7/2023"
published-title: "Due in class on"
# format:
#   latex:
#     include-in-header:
#       - text:
#           \usepackage{fancyhdr}
#     include-before-body:
#       - text:
#           \pagestyle{fancy}
#           \fancyhead[LH]{HW7}
#           \fancyhead[RH]{STAT425, Fall 2023}
---

1. Show that if $X = (X_1, X_2)$ is a random vector, then $\mathbb{E}\left[aX_1 + bX_2 + c\right] = a\mathbb{E}X_1 + b\mathbb{E}X_2 + c$. Establish the result in both the discrete and continuous cases.

2. (Covariance formula) Show that $\mathbb{E}\left[(X - \mathbb{E}X)(Y - \mathbb{E}Y)\right] = \mathbb{E}(XY) - \mathbb{E}X\mathbb{E}Y$.

3. Suppose $(X_1, X_2)$ are uniformly distributed on the unit square, *i.e.*, $$f(x_1, x_2) = 1\;,\qquad 0 < x_1 < 1, 0 < x_2 < 1$$ Find the distribution of $Y = X_1 + X_2$ by finding the CDF of $Y$.

4. Consider again the house hunting example from class where $X_1$ denotes the number of bedrooms and $X_2$ denotes the number of bathrooms, and for a randomly selected listing the vector $(X_1, X_2)$ has joint distribution:

|             | $x_1 = 0$ | $x_1 = 1$ | $x_1 = 2$ | $x_1 = 3$ |
|-------------|-----------|-----------|-----------|-----------|
| $x_2 = 1$   | 0.1       | 0.1       | 0.2       | 0         |
| $x_2 = 1.5$ | 0         | 0.1       | 0.2       | 0         |
| $x_2 = 2$   | 0         | 0         | 0         | 0.3       |
| $x_2 = 2.5$ | 0         | 0         | 0         | 0         |

Find the covariance and correlation of $X_1$ and $X_2$.

5. Let $(X_1, X_2)$ be independent exponential random variables with parameter $\beta = 2$, so that they have joint distribution $$f(x_1, x_2) = \frac{1}{4} \exp\left\{-\frac{1}{2}(x_1 + x_2)\right\}\;,\qquad x_1 > 0, x_2 > 0$$ Let $Y_1, Y_2$ denote the sum and difference, respectively, of $X_1, X_2$. Find the correlation $\text{corr}(Y_1, Y_2)$.

6. Suppose that you arrive at work within a 2-minute window of your expected arrival time uniformly at random, and your expected arrival time may shift slightly depending on whether there are traffic delays. That is, if $X$ denotes your arrival time where $X = 0$ indicates you are exactly on time, and $Y$ denotes the traffic delay, then assume:
$$
X|Y \sim \text{uniform}(Y - 1, Y + 1)
$$
If $Y \sim \text{exponential}(1)$, find the mean arrival time $\mathbb{E}X$.